### ISSUE TITLE
Save vrm scene as new scene result in large packed scene file

### ISSUE THREAD

**Issue by uslsneet** [V-Sekai/godot-vrm#107]
# Godot Version
4.2.2

# Description
When I save vrm scene as new scene, the size of resulting packed scene is a lot bigger(226MB) than original vrm scene(7.5MB).
(I am doing this because I want to modify node structure of my character, like add cloth mesh etc.)

# How to reproduce:
1. Create empty new scene
2. Drag vrm scene to new scene
3. Make vrm scene local
4. Save new scene
5. New scene(226MB) is a lot bigger than vrm scene(7.5MB).

**Comment by fire** [comment]
Please note that if you're counting the internal version of the vrm scene you must also count the files in .godot/ so they're similar in size. Do note that saving a scene or a resource text will cause the size to be quite big.

**Comment by lyuma** [comment]
I would also like to note that we have fixed some engine issues in Godot 4.3 with regard to the in-memory size of imported vrm meshes. I would expect the scene to be significantly smaller in godot 4.3rc1

but also, if your plan us to use "make local", it may make sense to extract the meshes, textures or materials using the advanced importer so that the textures and meshes will not be embedded in the scene

**Comment by uslsneet** [comment]
@fire @lyuma 
Your advices work.
After saving scene as binary(.scn) and extract meshes, textures and materials, file size is now reasonable. And I'm looking forward to godot 4.3. Thank you guys for developing this amazing plugin.
