### ISSUE TITLE
Animation causes the face to be black

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#18]
@Lyuma#0781 

Playing the A animation causes the face to be black.

https://github.com/V-Sekai/godot-vrm/commit/eb5938a535caf400f586bf2945610987a5a84a6d

Broken on both Windows and Linux.

https://user-images.githubusercontent.com/32321/120125511-fb800800-c16d-11eb-9b6a-0d94679edefa.mp4

**Comment by lyuma** [comment]
See here: this seems to be a Godot Engine bug.
https://github.com/godotengine/godot/issues/10402

This bug happens in the sample project because there are two copies of the same Alicia vrm visible on-screen at the same time. Godot has a limitation that a mesh with blendshapes must only be rendered once per frame.

The workaround is to make the face mesh (every mesh with blend shapes) use "resource_local_to_scene = true". This has the consequence of wasting memory as each mesh will be duplicated, potentially along with all embedded materials and textures.

I will have to consider what to do with the the sample scene, considering that a user may encounter this bug and be confused. On the other hand, it is a good limitation to be aware of, and having the bug easily reproducible will teach the user what happens.

**Comment by fire** [comment]
I think the demo should show our best possible case in graphical quality.
