### ISSUE TITLE
VRM export

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#41]
Godot has a bone map now and might actually open up vrm export as a possibility from godot

**Comment by fire** [comment]
> トカゲ — Today at 07:26
I'm working on a rest fixer right now that will override the rest, but I need to figure out how to handle unmapped bones.
I mean, I can write in the Profile that the bones that correspond to VRM HumanBone should be Quat(0,0,0;1), but I don't know what to do for the bones that are not VRM HumanBone. Well, you don't have to worry about it if it is VRM1

**Comment by fire** [comment]
> SkeletonProfile and SkeletonProfileEditor may be reused

**Comment by fire** [comment]
Work has started. Will make issues as they appear.

**Comment by lyuma** [comment]
Export for VRM1 is going to be supported.
https://github.com/V-Sekai/godot-vrm/tree/vrm1-wip

I'll leave this open until the implementation is finished.

There's a bit of a lack of public comment so I'm not exactly sure what features people are looking for:

For example, I'm not sure if people are going to be interested in VRM 0 export.

There are also some issues that have me concerned about the quality of the exported models. In particular, all textures are currently exporting as .png regardless of the input filetype, and they may be exporting DXT-compressed textures rather than the original.

For me, the value proposition is this helps test the importer, since we can perform round-trip export->import tests. This has already been helpful for uncovering some import bugs.

**Comment by lyuma** [comment]
Export support already merged into master.
