### ISSUE TITLE
Run-time adding vrm avatars to a scene are not supported in Desktop and Web Export of the project

### ISSUE THREAD

**Issue by ghghorbanzade** [V-Sekai/godot-vrm#72]
When I select the load_at_runtime_scene.tscn as the main scene of the project and export it for Windows or Web, the avatar can not be added to the scene, although it works fine in the editor.

**Comment by lyuma** [comment]
Good catch: I did not test runtime loading within export builds, so there could be bugs in that case. I will have to debug to see what's going on.

**Comment by lyuma** [comment]
@ghghorbanzade Are you sure you copied the .vrm files into your export directory?

The point of runtime export is to load a copy of the vrm without accessing it to the project. The Windows Desktop export worked fine immediately as soon as I copied the two VRM files it uses into the export directory:
![image](https://github.com/V-Sekai/godot-vrm/assets/39946030/574c7a06-0cf0-48cb-95c3-fffa74fb26ac)

Web is a different story. Due to how web browsers work, it is not possible to access files from disk in the same way you would in a desktop platform. When testing the web export, in the javascrtipt console, I see this error:
```
Vrm Bones.js:14103 USER ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
onPrintError @ Vrm Bones.js:14103
```
I believe this is expected behavior when attempting to load a non-exported "res://" URL at runtime. I would encourage you to change the example to download the runtime .vrm file into a buffer (`PackedByteArray`), and then use `GLTFDocument.append_from_buffer` with that.

(If you insist on using `append_from_file`, I would encourage you to read the documentation for the Godot web platform to learn which URLs can be safely accessed from a web export. For example, I believe files previously saved with `user://` will be available using the web FileSystem API.)

I was unable to reproduce the issue on Desktop Export. If you think this is still a bug with godot-vrm, can you please provide an exact reproduction project and steps to reproduce? Otherwise, I can close this issue if you are able to get `append_from_buffer` to work on web.

**Comment by lyuma** [comment]
Ah, I tried `load_at_runtime_scene` which does use `append_from_buffer` and I can confirm it works as well:
![image](https://github.com/V-Sekai/godot-vrm/assets/39946030/48aab392-6c69-48a3-bf6a-041996520db4)

The only issue I ran into is some models had mismatched `textures` and `images` arrays, which currently crashes Godot if using Basis Universal, due to issue godotengine/godot#80316 so I just checked load_at_runtime_scene.gd to disable basis universal for now, until the Godot bug is fixed. Perhaps try updating to that version to see if it solves your issue, but you didn't say if it was a crash or not.

**Comment by ghghorbanzade** [comment]
> Ah, I tried `load_at_runtime_scene` which does use `append_from_file` but using drag and drop api and I can confirm it works as well: ![image](https://user-images.githubusercontent.com/39946030/258613195-48aab392-6c69-48a3-bf6a-041996520db4.png)
> 
> The only issue I ran into is some models had mismatched `textures` and `images` arrays, which currently crashes Godot if using Basis Universal, due to issue [godotengine/godot#80316](https://github.com/godotengine/godot/issues/80316) so I just checked load_at_runtime_scene.gd to disable basis universal for now, until the Godot bug is fixed. Perhaps try updating to that version to see if it solves your issue, but you didn't say if it was a crash or not.

As you mentioned, commenting "state.handle_binary_image = GLTFState.HANDLE_BINARY_EMBED_AS_BASISU" worked for me. 
Thansk @lyuma.
