### ISSUE TITLE
vrm export makes file size larger

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-vrm#89]
[scilly_merged4.zip](https://github.com/V-Sekai/godot-vrm/files/13679390/scilly_merged4.zip) CC-BY from Jin

**Comment by lyuma** [comment]
> sparse blend shapes; and merged vertex buffer deduplication (from unity exports)

vertex buffer deduplication has been solved in Godot 4.3

Sparse blend shapes were implemented on gltf export in Godot 4.3 (it calculates and uses them if `sparse_accessor_storage_size < conventional_storage_size`).

Sparse blend shapes are not yet supported in the in-memory Godot mesh format, so imported meshes will still be somewhat large, but in terms of vrm export, this bug is solved in Godot 4.3
